/**
 * Pure billing rules (isomorphic, unit-tested; docs/DOMAIN_MODEL.md §5.4).
 * All money is bigint units of 1/10 000 (lib/utils/money.ts); JavaScript
 * numbers are never used for amounts.
 *
 * Rounding (one rule everywhere): every amount that reaches the ledger is a
 * multiple of the folio currency's minor unit, rounded half away from zero
 * exactly once. Taxes are calculated per posted line (line-level), each tax
 * rounded on its own; folio totals and balances are exact sums of those
 * rounded lines, so they never need rounding.
 */
import { addDays } from "@/modules/business-date/business-date.policy";
import { type MoneyUnits, divideHalfUp, minorUnitStep } from "@/lib/utils/money";

const PERCENT_SCALE = 100n * 10_000n; // a percent in money units: 16% = 160 000

// --- Taxes ----------------------------------------------------------------------------

export interface TaxRuleInput {
  id: string;
  code: string;
  name: string;
  calculation: "PERCENT" | "FLAT_PER_UNIT";
  /** NET: percent of the net amount. COMPOUND: percent of net + earlier taxes. */
  basis: "NET" | "COMPOUND";
  /** Percent (16% = 16.0000) or flat amount per unit, in money units. */
  rate: MoneyUnits;
  /** Order of application (TransactionCodeTax.sequence). */
  sequence: number;
  /** Code the generated tax line is posted with. */
  transactionCodeId: string;
}

export interface TaxLine {
  rule: TaxRuleInput;
  amount: MoneyUnits;
}

export interface ChargeBreakdown {
  net: MoneyUnits;
  taxes: TaxLine[];
  total: MoneyUnits;
}

function ordered(rules: readonly TaxRuleInput[]): TaxRuleInput[] {
  return [...rules].sort((a, b) => a.sequence - b.sequence || a.code.localeCompare(b.code));
}

function roundedDivide(numerator: bigint, denominator: bigint, step: bigint): MoneyUnits {
  return divideHalfUp(numerator, denominator * step) * step;
}

/** Forward calculation: the taxes generated by a net line amount. */
function taxesOnNet(
  net: MoneyUnits,
  quantity: number,
  rules: readonly TaxRuleInput[],
  step: bigint,
): TaxLine[] {
  const lines: TaxLine[] = [];
  let accumulated = 0n;
  for (const rule of ordered(rules)) {
    let amount: MoneyUnits;
    if (rule.calculation === "FLAT_PER_UNIT") {
      amount = roundedDivide(rule.rate * BigInt(quantity), 1n, step);
    } else {
      const base = rule.basis === "COMPOUND" ? net + accumulated : net;
      amount = roundedDivide(base * rule.rate, PERCENT_SCALE, step);
    }
    accumulated += amount;
    lines.push({ rule, amount });
  }
  return lines;
}

/**
 * Splits a posted line into net amount and generated taxes.
 *
 * - Exclusive (default): `amount` is the net; taxes are added on top.
 * - Inclusive: `amount` is the gross the guest pays. The net is estimated by
 *   dividing out the tax multiplier, taxes are calculated forward from that
 *   estimate, and the net is the gross minus those taxes — so net + taxes
 *   always equals the gross exactly (the rounding residual stays in the net).
 *
 * `amount` must already be a multiple of the minor unit; `quantity` is the
 * posting quantity (flat per-unit taxes).
 */
export function calculateCharge(input: {
  amount: MoneyUnits;
  quantity: number;
  inclusive: boolean;
  rules: readonly TaxRuleInput[];
  minorUnits: number;
}): ChargeBreakdown {
  const step = minorUnitStep(input.minorUnits);
  if (input.amount < 0n) throw new RangeError("A charge amount cannot be negative");
  if (input.amount % step !== 0n) throw new RangeError("Amount is not in currency minor units");
  if (!Number.isInteger(input.quantity) || input.quantity <= 0) {
    throw new RangeError("Quantity must be a positive integer");
  }

  if (!input.inclusive || input.rules.length === 0) {
    const taxes = taxesOnNet(input.amount, input.quantity, input.rules, step);
    return { net: input.amount, taxes, total: input.amount + sumTaxes(taxes) };
  }

  const rules = ordered(input.rules);
  let flat = 0n;
  // Tax multiplier 1 + S as an exact fraction num/den (percent rules only).
  let num = 0n;
  let den = 1n;
  for (const rule of rules) {
    if (rule.calculation === "FLAT_PER_UNIT") {
      flat += roundedDivide(rule.rate * BigInt(input.quantity), 1n, step);
      continue;
    }
    // t = rate/100 (NET) or rate/100 × (1 + S) (COMPOUND), with S the taxes so far.
    const tNum = rule.basis === "COMPOUND" ? rule.rate * (den + num) : rule.rate * den;
    const tDen = PERCENT_SCALE * den;
    num = num * tDen + tNum * den;
    den = den * tDen;
  }
  const remaining = input.amount - flat;
  const estimate = remaining > 0n ? roundedDivide(remaining * den, den + num, step) : 0n;
  const taxes = taxesOnNet(estimate, input.quantity, rules, step);
  const net = input.amount - sumTaxes(taxes);
  if (net < 0n) throw new RangeError("Taxes exceed the tax-inclusive amount");
  return { net, taxes, total: input.amount };
}

export function sumTaxes(taxes: readonly { amount: MoneyUnits }[]): MoneyUnits {
  return taxes.reduce((total, tax) => total + tax.amount, 0n);
}

/** Tax rules in force on a business date (inclusive effective range). */
export function rulesInForce<R extends { effectiveFrom: string; effectiveTo: string | null }>(
  rules: readonly R[],
  businessDate: string,
): R[] {
  return rules.filter(
    (rule) =>
      rule.effectiveFrom <= businessDate &&
      (rule.effectiveTo === null || rule.effectiveTo >= businessDate),
  );
}

// --- Adjustments ----------------------------------------------------------------------

export interface AdjustableLine {
  id: string;
  /** What is still on the folio for this line (original minus prior adjustments), >= 0. */
  remaining: MoneyUnits;
}

/**
 * Splits a credit of `amount` (tax included) across a charge line and its
 * tax lines in proportion to what remains of each. Each part is rounded to
 * the minor unit; the rounding residual is absorbed by the lines that still
 * have room, charge first, so the parts add up to `amount` exactly and no
 * line is credited beyond what remains of it.
 */
export function proportionalCredit(
  lines: readonly AdjustableLine[],
  amount: MoneyUnits,
  minorUnits: number,
): { id: string; amount: MoneyUnits }[] {
  const step = minorUnitStep(minorUnits);
  const total = lines.reduce((sum, line) => sum + line.remaining, 0n);
  if (amount <= 0n || amount > total) throw new RangeError("Adjustment outside the line total");
  if (amount % step !== 0n) throw new RangeError("Amount is not in currency minor units");
  if (amount === total) return lines.map((line) => ({ id: line.id, amount: line.remaining }));

  const parts = lines.map((line) => ({
    id: line.id,
    remaining: line.remaining,
    amount: roundedDivide(line.remaining * amount, total, step),
  }));
  let residual = amount - parts.reduce((sum, part) => sum + part.amount, 0n);
  for (const part of parts) {
    if (residual === 0n) break;
    if (residual > 0n) {
      const room = part.remaining - part.amount;
      const take = room < residual ? room : residual;
      part.amount += take;
      residual -= take;
    } else {
      const take = part.amount < -residual ? part.amount : -residual;
      part.amount -= take;
      residual += take;
    }
  }
  if (residual !== 0n) throw new RangeError("Adjustment cannot be allocated");
  return parts.map(({ id, amount: value }) => ({ id, amount: value }));
}

// --- Packages ---------------------------------------------------------------------------

export type PackageCalculation = "PER_ROOM" | "PER_PERSON" | "PER_ADULT" | "PER_CHILD";
export type PackagePostingRhythm =
  | "EVERY_NIGHT"
  | "ARRIVAL_NIGHT"
  | "LAST_NIGHT"
  | "EVERY_NIGHT_EXCEPT_ARRIVAL"
  | "EVERY_NIGHT_EXCEPT_LAST"
  | "WEEKDAYS"
  | "ONCE_PER_STAY";
export type PackagePostingType = "INCLUDED_IN_RATE" | "SEPARATE_LINE" | "COMBINED_WITH_ROOM";

export interface PackageComponentInput {
  componentId: string;
  name: string;
  transactionCodeId: string;
  postingType: PackagePostingType;
  calculation: PackageCalculation;
  rhythm: PackagePostingRhythm;
  /** Mon=1 … Sun=64 (WEEKDAYS rhythm). */
  daysOfWeek: number;
  /** Unit price for this night (seasonal price / reservation override resolved). */
  unitPrice: MoneyUnits;
  /** Packages booked more than once (ReservationPackage.quantity). */
  packageQuantity: number;
  isAllowance: boolean;
}

export interface PackageLine {
  componentId: string;
  name: string;
  transactionCodeId: string;
  postingType: PackagePostingType;
  quantity: number;
  unitPrice: MoneyUnits;
  amount: MoneyUnits;
}

const WEEKDAY_BITS = [64, 1, 2, 4, 8, 16, 32]; // indexed by getUTCDay(): Sunday = 0

function weekdayBit(date: string): number {
  return WEEKDAY_BITS[new Date(`${date}T00:00:00.000Z`).getUTCDay()]!;
}

function rhythmApplies(
  rhythm: PackagePostingRhythm,
  daysOfWeek: number,
  stay: { night: string; arrival: string; departure: string },
): boolean {
  const lastNight = addDays(stay.departure, -1);
  switch (rhythm) {
    case "EVERY_NIGHT":
      return true;
    case "ARRIVAL_NIGHT":
    case "ONCE_PER_STAY":
      return stay.night === stay.arrival;
    case "LAST_NIGHT":
      return stay.night === lastNight;
    case "EVERY_NIGHT_EXCEPT_ARRIVAL":
      return stay.night !== stay.arrival;
    case "EVERY_NIGHT_EXCEPT_LAST":
      return stay.night !== lastNight;
    case "WEEKDAYS":
      return (daysOfWeek & weekdayBit(stay.night)) !== 0;
  }
}

/**
 * The package lines one stay night generates. Allowance components (a
 * credit consumed by outlet postings) need the package ledger and are not
 * posted here.
 */
export function packageLinesForNight(
  components: readonly PackageComponentInput[],
  stay: { night: string; arrival: string; departure: string; adults: number; children: number },
): PackageLine[] {
  const lines: PackageLine[] = [];
  for (const component of components) {
    if (component.isAllowance) continue;
    if (!rhythmApplies(component.rhythm, component.daysOfWeek, stay)) continue;
    const persons =
      component.calculation === "PER_ROOM"
        ? 1
        : component.calculation === "PER_PERSON"
          ? stay.adults + stay.children
          : component.calculation === "PER_ADULT"
            ? stay.adults
            : stay.children;
    const quantity = persons * component.packageQuantity;
    if (quantity <= 0) continue;
    lines.push({
      componentId: component.componentId,
      name: component.name,
      transactionCodeId: component.transactionCodeId,
      postingType: component.postingType,
      quantity,
      unitPrice: component.unitPrice,
      amount: component.unitPrice * BigInt(quantity),
    });
  }
  return lines;
}

/**
 * The room line of a night after packages: included components are carved
 * out of the nightly rate (the night's total stays the rate), combined
 * components are added to it. Separate-line components do not touch it.
 */
export function roomLineAmount(rate: MoneyUnits, packages: readonly PackageLine[]): MoneyUnits {
  let amount = rate;
  for (const line of packages) {
    if (line.postingType === "INCLUDED_IN_RATE") amount -= line.amount;
    if (line.postingType === "COMBINED_WITH_ROOM") amount += line.amount;
  }
  if (amount < 0n) throw new RangeError("Included packages exceed the room rate");
  return amount;
}

// --- Posting keys -------------------------------------------------------------------------

/** Deterministic key of a room night's posting (generation counts re-postings after reversal). */
export function roomPostingKey(reservationRoomId: string, night: string, generation: number) {
  return `ROOM:${reservationRoomId}:${night}:${generation}`;
}

export function packagePostingKey(
  reservationRoomId: string,
  night: string,
  componentId: string,
  generation: number,
) {
  return `PKG:${reservationRoomId}:${night}:${componentId}:${generation}`;
}

// --- Folio and payment rules ----------------------------------------------------------------

export type FolioStatus = "OPEN" | "SETTLED" | "CLOSED";

/** Why a payment cannot be taken against a window with this balance (null = allowed). */
export function paymentProblem(amount: MoneyUnits, balance: MoneyUnits): string | null {
  if (amount <= 0n) return "The payment amount must be greater than zero";
  if (balance <= 0n) return "This window has no balance to pay";
  if (amount > balance) return "The payment is more than the balance due";
  return null;
}

export function refundProblem(
  amount: MoneyUnits,
  payment: { status: string; amount: MoneyUnits; refunded: MoneyUnits },
): string | null {
  if (payment.status !== "CAPTURED") return "Only a captured payment can be refunded";
  if (amount <= 0n) return "The refund amount must be greater than zero";
  if (amount > payment.amount - payment.refunded) {
    return "The refund is more than what remains refundable on this payment";
  }
  return null;
}

export function settleProblem(status: FolioStatus, balance: MoneyUnits): string | null {
  if (status === "CLOSED") return "The window is closed";
  if (status === "SETTLED") return "The window is already settled";
  if (balance !== 0n) return "Only a window with a zero balance can be settled";
  return null;
}

/** Whether a posting may be reversed on this business date (same-day corrections only). */
export function reversalProblem(
  item: { kind: string; businessDate: string; reversed: boolean; adjusted: boolean },
  businessDate: string,
): string | null {
  if (item.kind !== "CHARGE") return "Only charges can be reversed; taxes follow their charge";
  if (item.reversed) return "This charge has already been reversed";
  if (item.adjusted) return "This charge has been adjusted; adjust it further instead";
  if (item.businessDate !== businessDate) {
    return "Only charges posted today can be reversed; adjust earlier charges instead";
  }
  return null;
}
